In [1]:
import pandas as pd

In [3]:
cs = pd.read_csv("cust_season_N.csv", usecols = ["cust_nbr","year","fisc_wk_id","ttl_cases"])

In [8]:
cs.shape

(141778, 4)

In [9]:
cs.drop_duplicates()

        cust_nbr  year  fisc_wk_id  ttl_cases
0          36111  2021      202218        1.0
2          36111  2021      202219        1.0
7          36111  2021      202220        1.0
8          36111  2021      202221        1.0
9          36475  2021      202218        1.0
...          ...   ...         ...        ...
141773    952754  2023      202329        1.0
141774    952754  2023      202330        1.0
141775    952754  2023      202332        1.0
141776    952754  2023      202333        2.0
141777    952754  2023      202341        1.0

[84331 rows x 4 columns]

In [6]:
cs.head(60)

    cust_nbr  year  fisc_wk_id  ttl_cases
0      36111  2021      202218        1.0
1      36111  2021      202218        1.0
2      36111  2021      202219        1.0
3      36111  2021      202219        1.0
4      36111  2021      202219        1.0
5      36111  2021      202219        1.0
6      36111  2021      202219        1.0
7      36111  2021      202220        1.0
8      36111  2021      202221        1.0
9      36475  2021      202218        1.0
10     36475  2021      202218        2.0
11     36475  2021      202218        7.0
12     36475  2021      202218        2.0
13     36475  2021      202218        5.0
14     36475  2021      202218        2.0
15     36475  2021      202218        4.0
16     36475  2021      202218        2.0
17     36475  2021      202218       12.0
18     36475  2021      202218        1.0
19     36475  2021      202218        1.0
20     36475  2021      202218        2.0
21     36475  2021      202218        8.0
22     36475  2021      202218        4.0
23     36475  2021      202218        2.0
24     36475  2021      202218        1.0
25     36475  2021      202218        2.0
26     36475  2021      202218        6.0
27     36475  2021      202219        1.0
28     36475  2021      202219        2.0
29     36475  2021      202219        3.0
30     36475  2021      202219        8.0
31     36475  2021      202219        2.0
32     36475  2021      202219        3.0
33     36475  2021      202219        1.0
34     36475  2021      202219        1.0
35     36475  2021      202219        2.0
36     36475  2021      202219        2.0
37     36475  2021      202219       12.0
38     36475  2021      202219        4.0
39     36475  2021      202219        3.0
40     36475  2021      202219        2.0
41     36475  2021      202220        1.0
42     36475  2021      202220        1.0
43     36475  2021      202220        6.0
44     36475  2021      202220        2.0
45     36475  2021      202220        3.0
46     36475  2021      202220        4.0
47     36475  2021      202220        8.0
48     36475  2021      202220        2.0
49     36475  2021      202220        5.0
50     36475  2021      202220        1.0
51     36475  2021      202220        1.0
52     36475  2021      202220        1.0
53     36475  2021      202220        3.0
54     36475  2021      202220        6.0
55     36475  2021      202220        3.0
56     36475  2021      202220        1.0
57     36475  2021      202221        1.0
58     36475  2021      202221        1.0
59     36475  2021      202221        1.0

In [7]:
cs["ttl_cases"].value_counts()

1.000     66612
2.000     27964
3.000     12509
4.000      8885
5.000      4829
          ...
6.250         1
7.333         1
18.166        1
1.416         1
10.250        1
Name: ttl_cases, Length: 184, dtype: int64